FROM python:3.10.12

# Install necessary build tools and dependencies
RUN apt-get update \
    && apt-get install -y \
    cmake libsm6 libxext6 libxrender-dev protobuf-compiler \
    && rm -r /var/lib/apt/lists/*

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the python source code into the container
COPY model .

# Set the working directory to model
WORKDIR /app

# Install the necessary python packages
RUN pip install -r requirements.txt

# Expose the port FastAPI will use
EXPOSE 8000

# Command to run the FastAPI application

CMD ["uvicorn", "chatbot:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
# CMD ["python", "chatbot.py"]