services:
  db:
    image: postgres:12.19-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackutd2024
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    restart: always
    build:
      context: ./
      dockerfile: ./backend/dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      # - model

  # model:
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: ./model/dockerfile
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./model:/app

volumes:
  db_data:
    driver: local